# Generated by Django 6.1 on 2026-08-31 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_resume_education_embedding_and_more'),
        ('api', '0005_resume_owner'),
    ]

    operations = [
    ]
