# Generated by Django 6.1 on 2026-08-31 23:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20260831_2214'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='recruiter_requires_company_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('applicant', 'Applicant')], default='recruiter', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(('user_type', 'recruiter'), models.Q(('company_name', ''), _negated=True), _connector='OR'), name='recruiter_requires_company_name'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_recruiter',
        ),
    ]
