# Generated by Django 6.1 on 2026-08-31 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_userprofile_recruiter_requires_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='recruiter_requires_company_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company_name',
        ),
    ]
