# Generated by Django 6.1 on 2026-09-01 02:51

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_userprofile_recruiter_requires_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='summary_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
