# Generated by Django 6.1 on 2026-09-01 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_job_description_embedding_resume_summary_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='recruiter_requires_company_name',
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user_type', 'recruiter'), _negated=True), models.Q(('company_name', ''), _negated=True), _connector='OR'), name='recruiter_requires_company_name'),
        ),
    ]
