# Generated by Django 6.1 on 2026-09-01 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_userprofile_recruiter_requires_company_name_and_more'),
        ('api', '0009_remove_userprofile_recruiter_requires_company_name_and_more'),
    ]

    operations = [
    ]
