# Generated by Django 6.1 on 2026-09-01 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20260901_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_swiped_yes', models.BooleanField(blank=True, null=True)),
                ('employer_swiped_yes', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.resume')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'resume'), name='unique_mutual_match')],
            },
        ),
    ]
